version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: nest_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
    ports:
      - "5434:5432"  # host:container
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
